/* eslint-disable no-undef */

module.exports = {
	'extends': 'stylelint-config-standard-scss',
	'plugins': [
		'stylelint-order',
		'./aux/stylelint/stylelint-color-no-rgb.js'
	],
	'rules': {
		'indentation':'tab',
		'color-no-invalid-hex': true,
		'azeeson/color-no-rgb': true,
		'order/properties-order': [
			[
				'composes',
				'all',
				'position',
				'z-index',
				'top',
				'right',
				'bottom',
				'left',
				'display',
				'padding',
				'padding-top',
				'padding-right',
				'padding-bottom',
				'padding-left',
				'margin',
				'margin-top',
				'margin-right',
				'margin-bottom',
				'margin-left',
				'overflow',
				'width',
				'min-width',
				'max-width',
				'height',
				'min-height',
				'max-height',
				'box-sizing',
				'flex',
				'flex-basis',
				'flex-direction',
				'flex-flow',
				'flex-grow',
				'flex-shrink',
				'flex-wrap',
				'align-content',
				'align-items',
				'align-self',
				'justify-content',
				'order',
				'border',
				'border-width',
				'border-style',
				'border-color',
				'border-radius',
				'border-top',
				'border-top-width',
				'border-top-style',
				'border-top-color',
				'border-top-radius',
				'border-right',
				'border-right-width',
				'border-right-style',
				'border-right-color',
				'border-right-radius',
				'border-bottom',
				'border-bottom-width',
				'border-bottom-style',
				'border-bottom-color',
				'border-bottom-radius',
				'border-left',
				'border-left-width',
				'border-left-style',
				'border-left-color',
				'border-left-radius',
			],
			{unspecified: 'bottomAlphabetical'}
		],
	}
};
